name: Set up Dune
description: Install Dune and optionally build a project with Dune package management
author: Samuel Hym
inputs:
  version:
    description: 'Which version of the Dune binary to install'
    required: false
    default: 'dev'
  automagic:
    description: 'Whether to run automatically all the standard lock, build, test steps'
    required: false
    default: 'false'
  steps:
    description: 'Fine-grain control of the steps to run; override `automagic` when set'
    required: false
    default: ''
  directory:
    description: 'Directory in which dune should be run'
    required: false
    default: '.'
outputs:
  dune-cache-hit:
    description: 'A boolean value to indicate the Dune cache was found in the GHA cache'
    value: ${{ steps.dune-cache.outputs.cache-hit }}
runs:
  using: 'composite'
  steps:
    - name: Environment setup
      shell: bash
      run: |
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"
        echo "DUNE_CACHE_ROOT=$HOME/.cache/dune" >> "$GITHUB_ENV"
    - name: Cache dune’s cache
      uses: actions/cache@v4
      id: dune-cache
      with:
        path: |
          ${{ env.DUNE_CACHE_ROOT }}
        key: x2-dune-cache-${{ runner.os }}-${{ runner.arch }}
    - name: Run the main action script
      shell: bash
      env:
        DUNE_CONFIG__PKG_BUILD_PROGRESS: enabled
        SETUPDUNEVERSION: ${{ inputs.version }}
        SETUPDUNEDIR: ${{ inputs.directory }}
        SETUPDUNEAUTOMAGIC: ${{ inputs.automagic }}
        SETUPDUNESTEPS: ${{ inputs.steps }}
        OS: ${{ runner.os }}
        ACTIONPATH: ${{ github.action_path }}
      run: |
        bash "$ACTIONPATH/setupdune.sh"
    - name: Explore cache
      shell: bash
      run: |
        du -hsc "$DUNE_CACHE_ROOT"
        find "$DUNE_CACHE_ROOT"
        dune cache size
